language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install nose
  - python setup.py install
# command to run tests
script:
  - nosetests
